### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by ataulm**
This PR updates the library to use AndroidX dependencies. This means that we can update for bugfixes as they come out since changes aren't being shipped to the old support library anymore.

In terms of actual classes that changed, these are the only ones that are included in the library which have been migrated (apart from resource/nullability annotations):

- `AccessibilityDelegateCompat`
- `AccessibilityNodeInfoCompat`
- `AlertDialog`

**This will require a version bump since it won't be backwards compatible with projects that _haven't_ migrated to AndroidX yet.**

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Review by tasomaniac — APPROVED** [review]

**Comment by tasomaniac** [comment]
Looks good

**Review by mr-archano — APPROVED** [review]

**Comment by mr-archano** [comment]
The CI setup seems botched, I am about to look into that.
@ataulm what is the release process for this? It seems like no snapshot/automated releases are in place, right?

**Comment by ataulm** [comment]
I don't remember 😬

I believe when we wanted to make a release, there we would do one more PR with a version bump, trigger the release job manually on the CI and then create a new release on GH listing the PRs included since the last release.

I don't think there's a rush with releasing - there's no new features or bug fixes since the last release, so maybe it can wait til something else changes.

Existing apps using this can use the old artifact as long as they have jetifier enabled (if they're using android X) or just the old artifact if they haven't migrated their app project to android x

**Comment by mr-archano** [comment]
@hal90002 retest this please

**Pull request merged**
