### PR TITLE
Make AndroidVersion final and its constuctor private

### PR DESCRIPTION
**Pull request by takecare**
Close `AndroidVersion`.
Paired with @jackSzm.

### CODE REVIEW

**Comment by ouchadam** [comment]
what's the reasoning for this?

**Comment by rock3r** [comment]
Don't we have a template?

**Comment by takecare** [comment]
@ouchadam as it's not part of the public api of the library there's no need to have it exposed
@rock3r a pr template? not for this project i believe.

**Comment by ouchadam** [comment]
it's an internal package level class, it's already pretty closed off!

**Comment by rock3r** [comment]
@takecare yeah that's what I meant. Maybe @ataulm can do it? Or I can. Same.

As far as I'm concerned, I am a fan of the closed-by-default approach, but it would have to be the default one on the codebase, not an ad-hoc thing.

**Comment by takecare** [comment]
@rock3r as far as the project convention i don't think any is set atm. this was requested however but i'll be closing it now as it hinders its original purpose: testability.

**Comment by blundell** [comment]
we need to shhhtap making classes `final` Novoda convention is to not do this unless you have an explicit reason. Been bitten so many times by final class. Next you'll be asking for `final` method params ... we've been down this route already

**Comment by takecare** [comment]
@blundell i believe you have but it's actually good that the discussion re-surfaces from time to time so we all can be on the same page

**Comment by ataulm** [comment]
There is no project convention but there is a PMD/findbugs for _not_ making classes final if you only have private ctors. This is part of the Novoda ruleset unless some projects have been suppressing this warning without feeding back?

For public classes in libraries, I agree they should not be final.

For private or package-protected classes that aren't exposed from the library and aren't themselves tested, I don't see the harm in it, e.g. here, but there's no benefit either except for findbugs/pmd (which isn't yet applied on this project).

**Pull request closed without merging**
